// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASl-XLh2IrC0QGovtnPtUIF68WK37cq6E',
    appId: '1:970578196525:web:7fd412323775b9d95be0a4',
    messagingSenderId: '970578196525',
    projectId: 'movilescaracheo',
    authDomain: 'movilescaracheo.firebaseapp.com',
    storageBucket: 'movilescaracheo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwgMeAaAIK72BAEBzxtKGMLQzdxvb1OsU',
    appId: '1:970578196525:android:c6485a44701d684a5be0a4',
    messagingSenderId: '970578196525',
    projectId: 'movilescaracheo',
    storageBucket: 'movilescaracheo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn8IIh6TeFSN_LECrE54IKPHhCNQ4rKG8',
    appId: '1:970578196525:ios:5237622a662fd9ed5be0a4',
    messagingSenderId: '970578196525',
    projectId: 'movilescaracheo',
    storageBucket: 'movilescaracheo.firebasestorage.app',
    iosBundleId: 'com.example.movilesejmplo1',
  );
}
